#Requires -Version 5.1
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

Set-Location (Join-Path $PSScriptRoot '..\builtinFonts')

function Get-FontId {
    param([string[]]$Files)
    $sum = [System.Numerics.BigInteger]::Zero
    foreach ($f in $Files) {
        $bytes = [System.IO.File]::ReadAllBytes($f)
        $hash  = [System.Security.Cryptography.SHA256]::Create().ComputeHash($bytes)
        $hex   = [System.BitConverter]::ToString($hash) -replace '-', ''
        $sum  += [System.Numerics.BigInteger]::Parse('0' + $hex, [System.Globalization.NumberStyles]::HexNumber)
    }
    $mod = [System.Numerics.BigInteger]::Pow(2, 32)
    $val = [int64]($sum % $mod)
    if ($val -ge [System.Numerics.BigInteger]::Pow(2, 31)) { $val -= [int64][System.Numerics.BigInteger]::Pow(2, 32) }
    return $val
}

Write-Output '// The contents of this file are generated by ./lib/EpdFont/scripts/build-font-ids.ps1'
Write-Output '#pragma once'
Write-Output ''

$readerSizes = @(10, 12, 14, 16, 18)
$readerStyles = @('regular', 'bold', 'bolditalic', 'italic')

foreach ($size in $readerSizes) {
    $files = $readerStyles | ForEach-Object { ".\bookerly_${size}_${_}.h" }
    Write-Output "#define BOOKERLY_${size}_FONT_ID ($(Get-FontId $files))"
}

foreach ($size in $readerSizes) {
    $files = $readerStyles | ForEach-Object { ".\notosans_${size}_${_}.h" }
    Write-Output "#define NOTOSANS_${size}_FONT_ID ($(Get-FontId $files))"
}

$uiStyles = @('regular', 'bold')
foreach ($size in @(10, 12)) {
    $files = $uiStyles | ForEach-Object { ".\inter_ui_${size}_${_}.h" }
    Write-Output "#define UI_${size}_FONT_ID ($(Get-FontId $files))"
}

Write-Output "#define SMALL_FONT_ID ($(Get-FontId @('.\notosans_8_regular.h')))"
